### ISSUE TITLE
README.md page redesign

### ISSUE THREAD

**Issue by deveshvaidyaofficial** [deveshvaidyaofficial/PatternsinC#27]
Our repository https://github.com/deveshvaidyaofficial/PatternsinC.git has a mimalistic README.md page...
I invite contributions for redesign of the README.md page which describes the idea and goal of our repository.
It should also include a mention about contributing to open source and its benefits.

Looking forward to work and collaborate with all of you...

**Comment by vidhvath28** [comment]
kindly assign me this issue ,I will like to work on this issue.

**Comment by deveshvaidyaofficial** [comment]
Multiple contributors have share created pull requests for this issue..
The code will be merged once the conflict between the code is resolved
